<?php

declare(strict_types=1);

namespace Backendbase\Infrastructure\UseCase\Console\GoodHousekeeping;

use FilesystemIterator;
use Override;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use RuntimeException;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

use function getcwd;
use function str_contains;

class ClearCache extends Command
{
    #[Override]
    protected function configure(): void
    {
        $this
            ->setName('clear-cache')
            ->setDescription('Clears caches generated by the system');
    }

    #[Override]
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $currentDirectory = getcwd();
        if ($currentDirectory === false) {
            throw new RuntimeException('Could not resolve the current directory.');
        }

        $dir   = 'var/cache';
        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST,
        );

        foreach ($files as $fileInfo) {
            $command  = ($fileInfo->isDir() ? 'rmdir' : 'unlink');
            $realPath = $fileInfo->getRealPath();
            if ($realPath === false) {
                continue;
            }

            if (str_contains($realPath, '.git') || ! str_contains($realPath, $currentDirectory)) {
                continue;
            }

            $command($realPath);
        }

        return 1;
    }
}
